-- CON-87: reference data the squashed baseline must reproduce.
--
-- These rows were previously inserted by the seed_platforms,
-- seed_evergreen_campaign_type and campaign-type-phase migrations (with the
-- platform IDs rewritten to Sqids by later fix-up migrations). Captured here
-- as the final post-migration state. created_at/updated_at fall back to the
-- column DEFAULT now(). JSON literals coerce into the jsonb columns.

INSERT INTO settings (key, value) VALUES ('setup_complete', 'false');

INSERT INTO platforms (id, name, post_types, cadence, constraints, image_constraints, pdf_constraints) VALUES
('zBU1zqVICGfk','Facebook','{"text-post":"Text post","image-post":"Image post","video":"Video","reel":"Reel (≤90s vertical)","story":"Story (24h ephemeral)","live-video":"Live video","carousel":"Carousel (multi-image)","poll":"Poll","event":"Event","link-post":"Link post (with OG preview card)"}','3–5 posts per week','varied formats; posts up to 63k chars; balanced tone','{"max_file_size_bytes":31457280,"allowed_formats":["jpeg","png","gif","webp"],"animated_gif_supported":true,"max_attachments_per_post":10}','{}'),
('rzgpTkARLH0L','Instagram','{"image-post":"Image post","carousel":"Carousel (up to 20 slides)","reel":"Reel (up to 15 min)","story":"Story (24h ephemeral)","live-video":"Live video","broadcast-channel":"Broadcast Channel (one-to-many messaging)","collaborative-post":"Collaborative post (co-authored)","guide":"Guide (curated collection)"}','4–7 posts per week','visual-first; captions up to 2200 chars; strong opening line','{"max_file_size_bytes":8388608,"allowed_formats":["jpeg","png"],"animated_gif_supported":false,"max_attachments_per_post":20}','{}'),
('AXqWG7U2qnpt','LinkedIn','{"text-post":"Text post","image-post":"Image post","carousel":"Carousel (PDF document)","video":"Video","article":"Article (long-form native blog)","poll":"Poll","newsletter":"Newsletter","event":"Event","live-video":"Live video"}','1–2 posts per week','professional tone; posts up to 3000 chars; articles up to 100k chars','{"max_file_size_bytes":10485760,"allowed_formats":["jpeg","png","gif"],"animated_gif_supported":false,"max_attachments_per_post":9}','{"max_file_size_bytes":104857600,"allowed_formats":["pdf"],"max_pages":300,"max_attachments_per_post":1}'),
('pQ4yxT3SuE57','Threads','{"text-post":"Text post","image-post":"Image post","carousel":"Carousel (up to 20 images/videos)","video":"Video","poll":"Poll","gif-post":"GIF post"}','3–5 posts per week','posts up to 500 chars; conversational tone','{"max_file_size_bytes":8388608,"allowed_formats":["jpeg","png","gif"],"animated_gif_supported":true,"max_attachments_per_post":20}','{}'),
('81mUCmc2xsKd','X (Twitter)','{"text-post":"Text post","image-post":"Image post","video":"Video","long-form-post":"Long-form post (formerly Twitter Notes / Articles)","poll":"Poll","space":"Space (live audio)","thread":"Thread (multi-post sequence)"}','3–5 posts per week','posts max 280 chars; use threads for longer content','{"max_file_size_bytes":5242880,"allowed_formats":["jpeg","png","webp","gif"],"animated_gif_supported":true,"max_attachments_per_post":4}','{}'),
('8S8bWQTG6qD','YouTube','{"video":"Video (standard long-form)","short":"Short (≤60s vertical)","live-stream":"Live stream","premiere":"Premiere (scheduled video with live chat)","community-post":"Community post (text/image/poll in the Community tab)","podcast":"Podcast (audio-first format via YouTube Music integration)"}','1 video per week','video-first; titles up to 100 chars; descriptions up to 5000 chars','{"max_file_size_bytes":16777216,"allowed_formats":["jpeg","png","gif"],"animated_gif_supported":true,"max_attachments_per_post":1}','{}');

INSERT INTO campaigns_types (id, name, label, description, is_system) VALUES
('Uk','awareness','Awareness','Increase brand/product visibility among new audiences.',TRUE),
('Ef','conversion','Conversion','Drive a specific action — purchase, signup, demo request, subscription.',TRUE),
('gb','engagement','Engagement','Build interactive relationships with the audience; increase frequency and depth of interaction.',TRUE),
('uw','evergreen','Evergreen','Build and maintain timeless content that retains value over months and years — definitive guides, cornerstone explainers, and reference material that compounds in search and social as it ages.',TRUE),
('Vq','retention','Retention','Keep existing customers active, loyal, and expanding usage.',TRUE);

INSERT INTO campaigns_types_phases (id, campaign_type_id, name, purpose, sequence) VALUES
('M2','Ef','Capture','Catch intent and pull prospects into a decision-making context. Landing page copy (single-CTA, segment-specific), lead capture content (whitepapers, ROI calculators, free trial prompts, demo CTAs), retargeting ad copy (sequenced benefit-driven creative), search-intent content (comparison pages, "best X for Y" guides, alternative-to pages, pricing breakdowns), social proof assets (testimonials, case study summaries, review compilations, trust badge copy).',1),
('pr','Ef','Nurture & Persuade','Build the case for prospects who didn''t convert on first contact. Email nurture sequences (value → social proof → objection handling → direct offer), full case studies and success stories (industry/role-matched), objection-handling content (FAQ copy, myth-busting posts, security/compliance docs, comparison charts), demo and walkthrough content (product tour scripts, video walkthrough scripts, sandbox guides), urgency and scarcity content (limited-time offer copy, countdown messaging), personalized outreach templates (abandoned-cart emails, pricing-page-visit triggers).',2),
('so','Ef','Close & Validate','Final push and immediate post-conversion reassurance. Last-mile content (guarantees, "cancel anytime" messaging, security certifications, real-time social proof copy), onboarding content (welcome emails, getting-started guides, first-value tutorials, setup wizard copy), confirmation and celebration content (order confirmations, thank-you page copy, "you''re in" emails), feedback capture content (post-purchase survey copy, "how did you hear about us" prompts).',3),
('98','Uk','Launch & Distribution','Generate initial reach through high-impact content. Hero content (anchor piece carrying the campaign narrative), hub content (supporting pieces that elaborate on the hero''s theme — blog posts, infographics, expert interviews), hygiene/help content (searchable evergreen pieces — how-tos, explainers, glossaries), social-native content (platform-specific short-form — reels, carousels, stories, threads), paid creative (display ads, sponsored posts, pre-roll).',1),
('xh','Uk','Sustain & Optimize','Maintain momentum and extend campaign reach. Refreshed variants (new angles/formats of existing assets to combat fatigue), user-generated and earned content (amplifying mentions, resharing audience reactions), retargeting content (sequenced messaging for people who engaged earlier), recap and proof content (milestone posts, highlight reels, social proof).',2),
('48','Vq','Activate & Embed','Establish habits and deliver first value post-conversion. Onboarding sequences (step-by-step guides, welcome email series, first-use tutorials), quick-win content (short tutorials, "do this in 5 minutes" templates, starter configurations), milestone celebration content ("you''ve completed your first X," progress updates), integration and ecosystem content (tool connection guides, workflow templates, API quickstarts), assigned support content (account manager introductions, personalized check-in emails).',1),
('qp','Vq','Deepen & Expand','Increase usage breadth and emotional investment. Advanced feature education ("did you know..." emails, feature-specific tutorials), use case content (stories showing different ways to use the product beyond initial purpose), community content (forum prompts, user group announcements, meetup/event content), exclusive and loyalty content (early access announcements, insider roadmap previews, loyalty rewards, anniversary perks), customer education content (certification materials, masterclass outlines, learning path descriptions), co-creation content (beta program invitations, feature request prompts, advisory council content).',2),
('Jg','Vq','Sustain & Recover','Maintain relationship and prevent/reverse churn. Health-monitoring content (usage report copy, ROI summary templates, "your year in review" copy), proactive check-in content ("how''s it going" emails, QBR preparation docs, satisfaction survey copy), re-engagement sequences (usage-drop triggers, "here''s what''s new" updates, help offers), win-back campaigns (exit survey copy, special offers, "here''s what''s changed" updates, personal outreach templates), advocacy and referral content (referral program copy, review requests, case study invitations, ambassador program materials), renewal and upgrade content (renewal reminders, upgrade path comparisons, ROI justification templates).',3),
('PQ','gb','Activate','Spark the first interaction. Conversation starters (polls, questions, opinion prompts), interactive content (quizzes, calculators, assessments), lead magnets (templates, checklists, mini-courses), live event content (webinar scripts, AMA prompts, live stream outlines), community seeding content (founding posts, tone-setting discussions).',1),
('C9','gb','Deepen','Increase engagement frequency and emotional investment. Serialized content (multi-part series, episodic content, recurring formats), UGC campaign content (challenges, contests, hashtag campaigns), collaborative content (co-created posts, expert roundups, guest takeovers, spotlights), exclusive access content (early previews, insider updates, members-only drops), personalized sequences (email nurture flows, segmented content paths).',2),
('YH','gb','Sustain & Compound','Make engagement self-reinforcing. Community-driven content (curated discussions, moderation prompts), feedback loop content (surveys, advisory board invitations), recognition content (leaderboards, contributor spotlights, badges), re-engagement content (win-back emails, fresh entry points for lapsed participants), bridge content (pieces introducing conversion themes — case studies, "how others use it" stories).',3),
('Kj','uw','Foundation','Build the cornerstone pieces the campaign will rely on for years. Pillar guides (definitive, comprehensive coverage of a topic), how-to and tutorial content (step-by-step with stable steps), explainers and definitions (glossaries, "what is X" pieces), reference content (comparisons, decision frameworks, checklists), and originals worth citing (research summaries, primary-source synthesis). Optimize for search intent that does not decay (informational, navigational, comparison).',1),
('hD','uw','Distribute & Cross-Link','Spread the cornerstone reach across channels and weave it into the rest of the content graph. Channel-specific adaptations (long-form blog → carousel, threads, video, slide deck), internal cross-linking from newer pieces, syndication and republishing on partner channels, search-snippet optimization (FAQs, structured data, featured-snippet phrasing), and inclusion in onboarding / sales-enablement collateral so the asset earns reuse outside marketing.',2),
('IO','uw','Refresh & Compound','Keep evergreen content actually evergreen. Periodic updates (refresh statistics, swap dated examples, modernize screenshots, add new sections), audit and consolidation (merge overlapping pieces, redirect stale URLs), expansion based on what readers actually search for after landing (related-question content), and retirement of pieces that have aged past usefulness. Cadence: review every 6–12 months.',3);
