-- CON-87: Postgres baseline schema.
--
-- Squashed from the ~45 SQLite migrations into one clean Postgres baseline
-- (greenfield cutover, no data migration). Translation rules applied:
--   DATETIME / TIMESTAMP          -> TIMESTAMPTZ (standardised on UTC)
--   CURRENT_TIMESTAMP default     -> now()
--   BLOB                          -> BYTEA
--   INTEGER PK AUTOINCREMENT      -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   integer-boolean columns       -> BOOLEAN
--   REAL                          -> DOUBLE PRECISION (matches Go float64)
--   TEXT columns holding JSON      -> jsonb (only the columns backed by a
--                                    custom driver.Valuer/Scanner; opaque
--                                    verbatim blobs such as raw_json/payload
--                                    stay TEXT)
-- Sqids TEXT primary keys are generated in Go (models.NewID), so PK columns
-- stay TEXT. assets_chunks.embedding is a pgvector vector(768) with an HNSW
-- cosine index (CON-87 WS4), so similarity search runs in-database.
--
-- Tables are created in FK-dependency order because Postgres validates
-- foreign-key targets at CREATE TABLE time (SQLite did not, which let the
-- old migrations carry FK clauses that named the pre-rename campaign_types
-- table — those are corrected here to campaigns_types).

-- pgvector: enables the `vector` column type + similarity operators. Shipped
-- prebuilt in the pgvector/pgvector base image.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id            TEXT        PRIMARY KEY,
    name          TEXT        NOT NULL,
    email         TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL DEFAULT '',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
    id         TEXT        PRIMARY KEY,
    user_id    TEXT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE platforms (
    id                TEXT        PRIMARY KEY,
    name              TEXT        NOT NULL,
    post_types        jsonb       NOT NULL DEFAULT '{}',
    cadence           TEXT        NOT NULL DEFAULT '',
    constraints       TEXT        NOT NULL DEFAULT '',
    image_constraints jsonb       NOT NULL DEFAULT '{}',
    pdf_constraints   jsonb       NOT NULL DEFAULT '{}',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE campaigns_types (
    id          TEXT        PRIMARY KEY,
    name        TEXT        NOT NULL UNIQUE,
    label       TEXT        NOT NULL DEFAULT '',
    description TEXT        NOT NULL DEFAULT '',
    is_system   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE campaigns_types_phases (
    id               TEXT        PRIMARY KEY,
    campaign_type_id TEXT        NOT NULL REFERENCES campaigns_types (id) ON DELETE CASCADE,
    name             TEXT        NOT NULL,
    purpose          TEXT        NOT NULL DEFAULT '',
    sequence         INTEGER     NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE tags (
    id         TEXT        PRIMARY KEY,
    name       TEXT        NOT NULL,
    color      TEXT        NOT NULL DEFAULT '',
    created_by TEXT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE campaigns (
    id                   TEXT             PRIMARY KEY,
    name                 TEXT             NOT NULL,
    description          TEXT             NOT NULL DEFAULT '',
    target_persona       TEXT             NOT NULL DEFAULT '',
    key_messages         TEXT             NOT NULL DEFAULT '',
    tone_guidelines      TEXT             NOT NULL DEFAULT '',
    use_assets           BOOLEAN          NOT NULL DEFAULT FALSE,
    asset_ids            jsonb            NOT NULL DEFAULT '[]',
    target_platforms     jsonb            NOT NULL DEFAULT '[]',
    campaign_type_id     TEXT             NOT NULL REFERENCES campaigns_types (id),
    status               TEXT             NOT NULL DEFAULT 'draft',
    start_date           TIMESTAMPTZ,
    end_date             TIMESTAMPTZ,
    estimated_post_count INTEGER,
    budget               DOUBLE PRECISION,
    currency             TEXT             NOT NULL DEFAULT '',
    language             TEXT             NOT NULL DEFAULT '',
    tag_ids              jsonb            NOT NULL DEFAULT '[]',
    created_by           TEXT             NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ      NOT NULL DEFAULT now()
);

CREATE TABLE assets (
    id         TEXT        PRIMARY KEY,
    title      TEXT        NOT NULL,
    content    TEXT        NOT NULL,
    status     TEXT        NOT NULL DEFAULT 'ready'
        CHECK (status IN ('pending', 'processing', 'ready', 'partial', 'failed')),
    type       TEXT        CHECK (type IS NULL OR type IN ('MD', 'PDF')),
    tag_ids    jsonb       NOT NULL,
    created_by TEXT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE assets_chunks (
    id          TEXT        PRIMARY KEY,
    asset_id    TEXT        NOT NULL REFERENCES assets (id) ON DELETE CASCADE,
    chunk_index INTEGER     NOT NULL,
    page_start  INTEGER,
    page_end    INTEGER,
    content     TEXT        NOT NULL DEFAULT '',
    token_count INTEGER     NOT NULL DEFAULT 0,
    embedding   vector(768),
    model       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (asset_id, chunk_index)
);
CREATE INDEX idx_assets_chunks_asset_id ON assets_chunks (asset_id);
-- HNSW index for cosine-distance ANN search (embedding <=> query).
CREATE INDEX idx_assets_chunks_embedding ON assets_chunks USING hnsw (embedding vector_cosine_ops);

CREATE TABLE asset_files (
    id               TEXT        PRIMARY KEY,
    asset_id         TEXT        NOT NULL UNIQUE REFERENCES assets (id) ON DELETE CASCADE,
    original_name    TEXT        NOT NULL,
    mime_type        TEXT        NOT NULL,
    size_bytes       BIGINT      NOT NULL,
    s3_key           TEXT        NOT NULL,
    thumbnail_s3_key TEXT,
    page_count       INTEGER,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_asset_files_asset_id ON asset_files (asset_id);

CREATE TABLE posts (
    id                     TEXT        PRIMARY KEY,
    campaign_id            TEXT        NOT NULL REFERENCES campaigns (id) ON DELETE CASCADE,
    platform_id            TEXT        REFERENCES platforms (id) ON DELETE SET NULL,
    platform_post_type     TEXT,
    title                  TEXT        NOT NULL,
    content                TEXT        NOT NULL DEFAULT '',
    media_urls             jsonb       NOT NULL DEFAULT '[]',
    scheduled_at           TIMESTAMPTZ,
    published_at           TIMESTAMPTZ,
    status                 TEXT        NOT NULL DEFAULT 'draft',
    cta_type               TEXT        NOT NULL DEFAULT 'none',
    cta_url                TEXT        NOT NULL DEFAULT '',
    target_audience_notes  TEXT        NOT NULL DEFAULT '',
    used_asset_ids         jsonb       NOT NULL DEFAULT '[]',
    campaign_type_phase_id TEXT        REFERENCES campaigns_types_phases (id),
    publisher              TEXT        NOT NULL DEFAULT '',
    publisher_post_id      TEXT,
    publisher_status       TEXT        NOT NULL DEFAULT '',
    published_results      TEXT        NOT NULL DEFAULT '',
    failure_reason         TEXT        NOT NULL DEFAULT '',
    cloned_from_post_id    TEXT,
    created_by             TEXT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_posts_cloned_from_post_id ON posts (cloned_from_post_id) WHERE cloned_from_post_id IS NOT NULL;
CREATE UNIQUE INDEX idx_posts_publisher_post_id ON posts (publisher_post_id) WHERE publisher_post_id IS NOT NULL;

CREATE TABLE post_versions (
    id             TEXT        PRIMARY KEY,
    post_id        TEXT        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    version_number INTEGER     NOT NULL,
    content        TEXT        NOT NULL,
    note           TEXT        NOT NULL DEFAULT '',
    creator        TEXT        NOT NULL CHECK (creator IN ('assistant', 'user')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_post_versions_post_id ON post_versions (post_id);
CREATE UNIQUE INDEX idx_post_versions_post_version ON post_versions (post_id, version_number);

CREATE TABLE post_assistant_messages (
    id         TEXT        PRIMARY KEY,
    post_id    TEXT        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    role       TEXT        NOT NULL CHECK (role IN ('user', 'model')),
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_post_assistant_messages_post_id ON post_assistant_messages (post_id);

CREATE TABLE social_accounts (
    id             TEXT        NOT NULL PRIMARY KEY,
    platform       TEXT        NOT NULL,
    profile_id     TEXT        NOT NULL,
    username       TEXT        NOT NULL DEFAULT '',
    display_name   TEXT        NOT NULL DEFAULT '',
    avatar_url     TEXT        NOT NULL DEFAULT '',
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
    raw_json       TEXT        NOT NULL DEFAULT '{}',
    connected_at   TIMESTAMPTZ NOT NULL,
    last_synced_at TIMESTAMPTZ NOT NULL,
    deleted_at     TIMESTAMPTZ
);
CREATE INDEX idx_social_accounts_platform_active ON social_accounts (platform) WHERE deleted_at IS NULL;
CREATE INDEX idx_social_accounts_profile_active  ON social_accounts (profile_id) WHERE deleted_at IS NULL;

CREATE TABLE secret (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL UNIQUE,
    ciphertext  BYTEA       NOT NULL,
    nonce       BYTEA       NOT NULL,
    wrapped_dek BYTEA       NOT NULL,
    dek_nonce   BYTEA       NOT NULL,
    algorithm   TEXT        NOT NULL DEFAULT 'AES-256-GCM',
    kek_version INTEGER     NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE auto_publish_allowlist (
    platform_id TEXT        NOT NULL PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_attachments (
    id               TEXT        PRIMARY KEY,
    post_id          TEXT        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    position         INTEGER     NOT NULL,
    mime_type        TEXT        NOT NULL,
    size_bytes       BIGINT      NOT NULL,
    width            INTEGER     NOT NULL DEFAULT 0,
    height           INTEGER     NOT NULL DEFAULT 0,
    is_animated      BOOLEAN     NOT NULL DEFAULT FALSE,
    page_count       INTEGER     NOT NULL DEFAULT 0,
    checksum_sha256  TEXT        NOT NULL,
    s3_key           TEXT        NOT NULL,
    thumbnail_s3_key TEXT,
    created_by       TEXT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (post_id, position)
);
CREATE INDEX idx_post_attachments_post_id ON post_attachments (post_id);

CREATE TABLE post_logs (
    id              TEXT        PRIMARY KEY,
    post_id         TEXT        NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    event_timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    event_type      TEXT        NOT NULL,
    actor           TEXT        NOT NULL,
    from_status     TEXT,
    to_status       TEXT,
    payload         TEXT        NOT NULL DEFAULT '{}',
    summary         TEXT        NOT NULL DEFAULT ''
);
CREATE INDEX idx_post_logs_post_id         ON post_logs (post_id);
CREATE INDEX idx_post_logs_event_timestamp ON post_logs (event_timestamp);
CREATE INDEX idx_post_logs_event_type      ON post_logs (event_type);

CREATE TABLE post_evaluations (
    id                 TEXT             PRIMARY KEY,
    post_id            TEXT             NOT NULL UNIQUE REFERENCES posts (id) ON DELETE CASCADE,
    platform_id        TEXT             NOT NULL DEFAULT '',
    platform_post_type TEXT             NOT NULL DEFAULT '',
    caption_scoped     BOOLEAN          NOT NULL DEFAULT FALSE,
    overall_pct        DOUBLE PRECISION NOT NULL DEFAULT 0,
    result             jsonb            NOT NULL DEFAULT '{}',
    model_id           TEXT             NOT NULL DEFAULT '',
    input_hash         TEXT             NOT NULL DEFAULT '',
    created_at         TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ      NOT NULL DEFAULT now()
);

CREATE TABLE post_analytics (
    post_id              TEXT             PRIMARY KEY REFERENCES posts (id) ON DELETE CASCADE,
    publisher_post_id    TEXT             NOT NULL UNIQUE,
    impressions          INTEGER          NOT NULL DEFAULT 0,
    reach                INTEGER          NOT NULL DEFAULT 0,
    likes                INTEGER          NOT NULL DEFAULT 0,
    comments             INTEGER          NOT NULL DEFAULT 0,
    shares               INTEGER          NOT NULL DEFAULT 0,
    saves                INTEGER          NOT NULL DEFAULT 0,
    clicks               INTEGER          NOT NULL DEFAULT 0,
    views                INTEGER          NOT NULL DEFAULT 0,
    engagement_rate      DOUBLE PRECISION NOT NULL DEFAULT 0,
    platform_analytics   jsonb            NOT NULL DEFAULT '[]',
    sync_status          TEXT             NOT NULL DEFAULT '',
    metrics_last_updated TIMESTAMPTZ,
    last_refreshed_at    TIMESTAMPTZ      NOT NULL DEFAULT now(),
    raw_json             TEXT             NOT NULL DEFAULT '{}',
    created_at           TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ      NOT NULL DEFAULT now()
);
